# SITE CONFIGURATION
baseurl:
url: "https://jss367.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Julius' Data Science Blog                        # site's title
description: "A blog about data science, machine learning, artificial intelligence (AI), and computer vision" # used by search engines
avatar: assets/img/avatars/possum.jpg                   # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: Exploring the World Through Data Science and Machine Learning  # Change Blog header text
header_feature_image: assets/img/astro_header.jpg
header_feature_image_responsive: true
footer_text: >
   &copy; 2015-2024 Julius Simonelli. Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.
permalink: /:title.html                                 

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics:                                       # Measurement ID, e.g. "G-00000"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# PAGINATION
paginate: 7
paginate_path: "/page:num"

# BUILD SETTINGS
sass:
  style: compressed
  quiet_deps: true
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
